# Site settings
title: Building Safety & Joy
header-img: img/home-bg.png
email: jobs.katlars@proton.me
copyright_name: KatieLars
description: > # this means to ignore newlines until "baseurl:"
  Art, Wine, Code, and InfoSec
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: sleepycecy
github_username:  KatieLars
learn_profile: KatieLars
email_username: jobs.katlars@proton.me

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", vendor]

plugins: [jekyll-paginate, jekyll-feed]
